version: '3.7'
services:
  web-ticket:
    build:
      context: .
      dockerfile: deployments/api/dev/Dockerfile
    container_name: web-ticket
    depends_on:
      - mysql-ticket
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - go-modules-volume:/go/pkg/mod
    networks:
      - network-ticket

  mysql-ticket:
    image: mysql:latest
    container_name: mysql-ticket
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=ticket
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql/
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - network-ticket

networks:
  network-ticket:
    driver: bridge

volumes:
  mysql-volume:
  go-modules-volume:
