// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ticketAllocating_Purchasing

import (
	"github.com/Selahattinn/ticketAllocating-Purchasing/internal/api"
	"github.com/Selahattinn/ticketAllocating-Purchasing/internal/api/handler"
	"github.com/Selahattinn/ticketAllocating-Purchasing/pkg/healthcheck"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func InitHealthCheck() healthcheck.IHealthCheckHandler {
	iHealthCheckHandler := healthcheck.NewHealthCheckHandler()
	return iHealthCheckHandler
}

func InitRoute(l *logrus.Logger) api.IRoute {
	iHomeHandler := handler.NewHomeHandler()
	iRoute := api.NewRoute(iHomeHandler)
	return iRoute
}

// wire.go:

var repositoryProviders = wire.NewSet()

var serviceProviders = wire.NewSet()

var orchestratorProviders = wire.NewSet()

var handlerProviders = wire.NewSet(handler.NewHomeHandler)

var allProviders = wire.NewSet(
	repositoryProviders,
	serviceProviders,
	orchestratorProviders,
	handlerProviders,
)
