// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/mysql/mysql.go

// Package mocks is a generated GoMock package.
package mocks

import (
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIMysqlInstance is a mock of IMysqlInstance interface.
type MockIMysqlInstance struct {
	ctrl     *gomock.Controller
	recorder *MockIMysqlInstanceMockRecorder
}

// MockIMysqlInstanceMockRecorder is the mock recorder for MockIMysqlInstance.
type MockIMysqlInstanceMockRecorder struct {
	mock *MockIMysqlInstance
}

// NewMockIMysqlInstance creates a new mock instance.
func NewMockIMysqlInstance(ctrl *gomock.Controller) *MockIMysqlInstance {
	mock := &MockIMysqlInstance{ctrl: ctrl}
	mock.recorder = &MockIMysqlInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMysqlInstance) EXPECT() *MockIMysqlInstanceMockRecorder {
	return m.recorder
}

// Database mocks base method.
func (m *MockIMysqlInstance) Database() *sql.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Database")
	ret0, _ := ret[0].(*sql.DB)
	return ret0
}

// Database indicates an expected call of Database.
func (mr *MockIMysqlInstanceMockRecorder) Database() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Database", reflect.TypeOf((*MockIMysqlInstance)(nil).Database))
}
